// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaaixaooootqtwhyltxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhYWl4YW9vb290cXR3aHlsdHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mzk1NTAsImV4cCI6MjA2OTExNTU1MH0.z7QTbbd_TQw2EFsAGi3J3nCsDaZwmc0UPyte_L94ubc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});